# https://docs.github.com/en/actions/sharing-automations/reusing-workflows

name: pipeline

on:
  workflow_call:
    inputs:
      # Required ======================
      version:
        required: true
        type: string
      # Optional ======================
      bake-convention:
        required: false
        default: 'default'
        type: string
      bake-version:
        required: false
        default: '0.37.51'
        type: string
      bake-destination:
        required: false
        default: 'nuget>github,container>rasmus,release>github,helm-chart>chart-museum@http://chart-museum.chart-museum/'
        type: string
      git-lfs:
        required: false
        type: string
      dotnet-version:
        required: false
        default: '8.0.x'
        type: string
      dotnet-environment:
        required: false
        default: 'Development'
        type: string
      helm-version:
        required: false
        default: '3.16.2'
        type: string
      helm-install:
        required: false
        type: string
      kind-install:
        required: false
        type: string
      kind-version:
        required: false
        default: 'v0.25.0'
        type: string
      docker-compose-up-timeout:
        required: false
        default: '300'
        type: string
      docker-compose-failed-logs-tail:
        required: false
        default: '512' # can be 'all'
        type: string
      tailscale-enabled:
        required: false
        type: string
      # Workflow inputs ======================
      cancel-in-progress:
        required: false
        type: boolean
        default: true
      self-hosted:
        required: false
        default: true
        type: boolean
    secrets:
      tailscale-oauth-client-id:
        required: false
      tailscale-oauth-client-secret:
        required: false
      tailscale-exit-node:
        required: false
      github-packages-token:
        required: false
      dockerhub-password:
        required: false

jobs:
  build:
    runs-on: ${{ !inputs.self-hosted && 'ubuntu-latest' || fromJSON('["self-hosted", "ubuntu-latest"]') }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: ${{ !contains(github.ref, 'release') && inputs.cancel-in-progress }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Get Bake
      uses: actions/checkout@v4
      with:
        repository: rasmus/workflow-bake
        ref: ${{ github.workflow_sha}}
        path: ${{ github.workspace }}/bake-workflow
  
    - name: Run Bake
      uses: ./
      with:
        # Required ======================
        version: ${{ inputs.version }}
        # Optional ======================
        bake-convention: ${{ inputs.bake-convention }}
        bake-version: ${{ inputs.bake-version }}
        bake-destination: ${{ inputs.bake-destination }}
        git-lfs: ${{ inputs.git-lfs }}
        dotnet-version: ${{ inputs.dotnet-version }}
        dotnet-environment: ${{ inputs.dotnet-environment }}
        helm-version: ${{ inputs.helm-version }}
        helm-install: ${{ inputs.helm-install }}
        kind-install: ${{ inputs.kind-install }}
        kind-version: ${{ inputs.kind-version }}
        docker-compose-up-timeout: ${{ inputs.docker-compose-up-timeout }}
        docker-compose-failed-logs-tail: ${{ inputs.docker-compose-failed-logs-tail }}
        tailscale-enabled: ${{ inputs.tailscale-enabled }}
        # Secrets ======================
        tailscale-oauth-client-id: ${{ secrets.tailscale-oauth-client-id }}
        tailscale-oauth-client-secret: ${{ secrets.tailscale-oauth-client-secret }}
        tailscale-exit-node: ${{ secrets.tailscale-exit-node }}
        github-packages-token: ${{ secrets.github-packages-token }}
        dockerhub-password: ${{ secrets.dockerhub-password }}
