# https://docs.github.com/en/actions/sharing-automations/reusing-workflows

name: pipeline

on:
  workflow_call:
    inputs:
      # Required ======================
      version:
        required: true
        type: string
      # Optional ======================
      bake-convention:
        required: false
        default: 'default'
        type: string
      bake-version:
        required: false
        type: string
        default: '0.31.44-beta'
      bake-destination:
        required: false
        default: 'nuget>github,container>rasmus,release>github,helm-chart>chart-museum@http://chart-museum.chart-museum/'
        type: string
      git-lfs:
        required: false
        type: boolean
        default: true
      dotnet-version:
        required: false
        type: string
        default: '8.0.x'
      cancel-in-progress:
        required: false
        type: boolean
        default: true
      dotnet-environment:
        required: false
        type: string
        default: 'Development'
      helm-version:
        required: false
        type: string
        default: '3.16.2'
      helm-install:
        required: false
        type: boolean
        default: true
      kind-install:
        required: false
        type: boolean
        default: false
      kind-version:
        required: false
        type: string
        default: 'v0.25.0'
      self-hosted:
        required: false
        type: boolean
        default: true
      docker-compose-up-timeout:
        required: false
        type: number
        default: 300
      docker-compose-failed-logs-tail:
        required: false
        type: string
        default: '512' # can be 'all'
    secrets:
      github-packages-token:
        required: false
      dockerhub-password:
        required: false

jobs:
  build:
    runs-on: ${{ !inputs.self-hosted && 'ubuntu-latest' || fromJSON('["self-hosted", "ubuntu-latest"]') }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: ${{ !contains(github.ref, 'release') && inputs.cancel-in-progress }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: ${{ inputs.git-lfs }}

    - name: Install Helm
      if: inputs.helm-install
      uses: azure/setup-helm@v4
      with:
        version: '${{ inputs.helm-version }}'

    - name: Install kind
      if: inputs.kind-install
      uses: helm/kind-action@v1
      with:
        install_only: true
        version: ${{ inputs.kind-version }}

    - name: Docker Hub login
      run: |
        if [ -n "${{ secrets.dockerhub-password }}" ]; then
          echo "${{ secrets.dockerhub-password }}" | docker login -u rasmus --password-stdin
        fi

    - name: Docker compose up (if present)
      run: |
        if [ -f docker-compose.yml ]; then
          echo "Docker compose file found, starting services in $PWD..."
          docker-compose up \
            --detach \
            --wait \
            --quiet-pull \
            --wait-timeout ${{ inputs.docker-compose-up-timeout }}
        fi

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '${{ inputs.dotnet-version }}'

    - name: Setup GitHub NuGet source
      run: |
        if [ -n "${{ secrets.github-packages-token }}" ]; then
          dotnet nuget add source \
            --username rasmus \
            --password ${{ secrets.github-packages-token }} \
            --store-password-in-clear-text \
            --name github-rasmus \
            "https://nuget.pkg.github.com/rasmus/index.json" || true
        fi

    - name: Bake it
      env:
        dockerhub_username: rasmus
        dockerhub_password: ${{ secrets.dockerhub-password }}
        ASPNETCORE_ENVIRONMENT: ${{ inputs.dotnet-environment }}
        DOTNET_ENVIRONMENT: ${{ inputs.dotnet-environment }}
        DOCKER_BUILDKIT: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet tool install --global Bake --version ${{ inputs.bake-version }}
        export PATH="$PATH:/home/ubuntu/.dotnet/tools"

        bake run \
          --convention=${{ inputs.bake-convention }} \
          --build-version ${{ inputs.version }} \
          --destination="${{ inputs.bake-destination }}"

    - name: Print Docker compose logs on failure
      if: failure()
      run: |
        if [ -f docker-compose.yml ]; then
          docker-compose logs \
            -t \
            --no-color \
            --tail ${{ inputs.docker-compose-failed-logs-tail }}
        fi
